---
title: "Statistical Learning"
author: "Yifei Yu"
date: "2024-10-29"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

```{r}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 6,
  fig.asp = 0.6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

load key packages.

```{r}
library(tidyverse)
library(glmnet)
set.seed(1031)
```


### Try Lasso!

import and clean birthweight data

```{r}
bwt_df =
  read_csv("data/birthweight.csv") |> 
  janitor::clean_names() |> 
  mutate(
    babysex =
      case_match(babysex,
                 1 ~ "male",
                 2 ~ "female"),
    babysex = fct_infreq(babysex),
    frace = 
      case_match(frace,
                 1 ~ "white",
                 2 ~ "black",
                 3 ~ "asian",
                 4 ~ "puerto rican",
                 5 ~ "other"),
    frace = fct_infreq(frace),
    mrace = 
      case_match(mrace,
                 1 ~ "white",
                 2 ~ "black",
                 3 ~ "asian",
                 4 ~ "puerto rican",
                 5 ~ "other"),
    mrace = fct_infreq(mrace)
  ) |> 
  sample_n(200)
```


Construct inputs for `glmnet`

```{r}
x = model.matrix(bwt ~ ., data = bwt_df)[, -1]
y = bwt_df |>  pull(bwt)
```



Fit lasso for several lambdas


```{r}
lambda = 10^seq(-2, 2.75, by = 0.1)

lasso_fit = glmnet(x = x, y = y, lambda = lambda)

lasso_cv = 
  cv.glmnet(x = x, y = y, lambda = lambda)

lambda_opt = lasso_cv[["lambda_min"]]
```


Usual lasso plot

```{r}
lasso_fit |> 
  broom::tidy() |> 
  filter(term != "(intercept)") |> 
  select(term, lambda, estimate) |> 
  complete(term, lambda, fill = list(estimate = 0)) |> 
  ggplot(aes(x = lambda, y = estimate, group = term, color = term)) +
  geom_vline(xintercept = lambda_opt, color = "red") +
  geom_line()
```



```{r}
final_lasso_fit = 
  glmnet(x = x, y = y, lambda = lambda_opt)

final_lasso_fit |> 
  broom::tidy()
```


Look at cv results.

```{r}
lasso_cv |> 
  broom::tidy() |> 
  ggplot(aes(x = log(lambda, 10), y = estimate)) +
  geom_point()
```




## Cluster Pokemons

```{r}
pokemon_df = 
  read_csv("data/pokemon.csv") |> 
  janitor::clean_names() |> 
  select(hp, speed)
```


```{r}
pokemon_df |> 
  ggplot(aes(x = hp, y = speed)) +
  geom_point()
```


Let's use kmeans to cluster these pokemon.

```{r}
kmeans_fit = 
  kmeans(x = pokemon_df, centers = 3)
```


Can i plot these results?

```{r}
pokemon_df =
  broom::augment(kmeans_fit, pokemon_df)
```


```{r}
pokemon_df |> 
  ggplot(aes(x = hp, y = speed, color = .cluster)) +
  geom_point()
```


